#ifndef EDITORSETTINGS_H
#define EDITORSETTINGS_H

//THE SETTINGS FILE OF THE EDITOR, INCLUDING FONTS AND FORMATTING PARAMETERS

typedef class editorSettings {



} settings;

#endif // EDITORSETTINGS_H
